### Get all contacts
GET https://cse341-node-9dp6.onrender.com/contacts
Accept: application/json

### Get a contact by id
GET https://cse341-node-9dp6.onrender.com/contacts/6742813e22c10d709ce17aa4
Accept: application/json